### ISSUE TITLE
Nice Work

### ISSUE THREAD

**Issue by glepnir** [IcyHeartBX/thinkvim-study#1]
Hi  i am the author of thinkvim, good repo to study vim,keep work,vi is the best editor ~\(≧▽≦)/~

**Comment by pixb** [comment]
thx u very much:-D

**Comment by pixb** [comment]
thx u very much:-D

**Comment by pixb** [comment]
> Hi i am the author of thinkvim, good repo to study vim,keep work,vi is the best editor ~(≧▽≦)/~

thank u very much:-D

**Comment by HanyuWu** [comment]
Learning vim scripts from today and see your repo, good repo. Hope I can master VIM someday too !
